
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomSupabaseRpcFunctions } from './rpc-types';

const SUPABASE_URL = "https://qzjfjkcwhjmxuhaoiqhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6amZqa2N3aGpteHVoYW9pcWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDAyMTEsImV4cCI6MjA2MDIxNjIxMX0.brYomlyGbhbFyJ6HdRoym4VLTH_CXS-6gIgHc_2A8xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Extend the Database type to include our custom RPC functions
type ExtendedDatabase = Database & {
  rpc: CustomSupabaseRpcFunctions;
};

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
